name: Rust

on:
  push:
    branches: [ "wasm" ]
  pull_request:
    branches: [ "wasm" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-wasi
    - name: Enable cache
        uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-component
    - run: cargo component build
    - run: cargo component test
